[package]
name = "sized-dst"
version = "0.1.0"
edition = "2021"

[features]
std = [] # impls of std traits

[dependencies]
aligned = "0.4.2"

[dev-dependencies]
static_assertions = "1.1"
trybuild = "1"
futures-executor = "0.3.30"
